"""Add rank to employee objects

Revision ID: b4f286a0162d
Revises: 3ca129635df8
Create Date: 2026-08-04 14:43:33.916304

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'b4f286a0162d'
down_revision = '3ca129635df8'
branch_labels = None
depends_on = None

def upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('rank_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'employee', 'rank', ['rank_id'], ['id'])
    op.drop_index(op.f('ix_jumpseat_request_rank'), table_name='jumpseat_request')
    op.drop_column('jumpseat_request', 'rank')
    # ### end Alembic commands ###

def downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jumpseat_request', sa.Column('rank', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_jumpseat_request_rank'), 'jumpseat_request', ['rank'], unique=False)
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'rank_id')
    # ### end Alembic commands ###
